title: Project
  columns:
    -width: 1/2
      sections:
        info:
          type: fields
          fields:
            heading: text
            subheading: text
            intro: text
            text: text
            link:
            type: url
    -width: 1/2
      sections:
        gallery:
        type: files
        layout: cards
          image:
            ratio: 1/1







